---
# tasks file for post_patching
- name: Service Revalidation
  include_tasks: linux_service_revalidation.yml

- name: Resource health check
  include_tasks: linux_resource_health_check.yml

- name:  Find out services not started after patch 
  include_tasks: linux_service_diff.yml

- name: Generate service report
  include_tasks: linux_report_generation.yml

- name: Copy evidences to controller node from linux machine
  include_tasks: linux_collect_evidence_to_share.yml

- name: Send notification
  include_tasks: notification.yml

- name: Perform cleanup
  include_tasks: linux_perform_cleanup.yml
