#SPDX-License-Identifier: MIT-0
---
# tasks file for pre-patching
- name: Create temp directory
  include_tasks: linux_create_temp_dir.yml

- name:  Validate patch 
  include_tasks: linux_validate_patch.yml

- name: Verify resources
  include_tasks: linux_verify_resources.yml

- name: Gather active services
  include_tasks: linux_gather_active_services.yml

- name: Gather Evidences
  include_tasks: linux_gather_evidences.yml